# Generated by Django 3.1.7 on 2022-12-06 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Utilisateur',
        ),
    ]
